{{- if .Values.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "magout.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.httproute.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hostnames:
    - {{ .Values.serverName }}
  parentRefs:
    {{- with .Values.httproute.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ''
          kind: Service
          name: {{ include "magout.fullname" . }}-gateway
          port: {{ .Values.gateway.service.port }}
          weight: 1
      {{- with .Values.httproute.timeouts }}
      timeouts:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
